# -*- coding: utf-8 -*-
"""Emmanuellayadeweek14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15LBnPfl3RQNrt4EpqJIjNVmkpIcljf1g
"""

import pandas as pd
import matplotlib.pyplot as plt
   
data = {'Year': [1920,1930,1940,1950,1960,1970,1980,1990,2000,2010],
        'Unemployment_Rate': [9.8,12,8,7.2,6.9,7,6.5,6.2,5.5,6.3]
       }
  
df = pd.DataFrame(data,columns=['Year','Unemployment_Rate'])
df
ax = plt.gca()

df.plot(kind='line',x='Year',y='Unemployment_Rate',ax=ax)


plt.show()